notifications:
  email: false

language: go

go: 1.8.3

before_install:
  - make prepare

install:
  - make dep

script:
  - make test
  - make lint
  - make vet
  - make build

branches:
  only:
    - master
