notifications:
  email: false

language: go

go: 1.8.3

before_install:
  - sudo ln -nfs /bin/bash /bin/sh
  - make prepare

install:
  - make dep

script:
  - make unit-test
  - make package-test
  - make integration-test
  - make shell-test
  - make lint
  - make vet

branches:
  only:
    - master
