notifications:
  email: false

language: go

go: 1.8.3

before_install:
  - sudo ln -nfs /bin/bash /bin/sh
  - make prepare

install:
  - make dep

before_script:
  - sudo cp -v ci_docker_daemon.json /etc/docker/daemon.json
  - sudo killall -v dockerd && sudo rm -f /var/run/docker.pid && sudo dockerd 2>&1 | logger -t dockerd &
  - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
  - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD} registry.hub.docker.com
  - cp ~/.docker/config.json docker.json
  - git remote set-url --push origin https://${GITHUB_TOKEN}@github.com/ivanilves/lstags.git

script:
  - make docker-image-async DOCKER_TAG=release
  - make unit-test
  - make whitebox-integration-test
  - make blackbox-integration-test
  - make lint
  - make vet
  - make docker-image-wait DOCKER_TAG=release TIMEOUT=120

after_script:
  - sudo killall -v dockerd

before_deploy:
  - make release

deploy:
  provider: script
  script: make deploy GITHUB_TOKEN=${GITHUB_TOKEN}
  skip_cleanup: true
  on:
    branch: master

branches:
  only:
    - master
